version: '3.0'

services:

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=docker.site
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
#      - ./html/:/var/www/html/
      - ./source/public/:/var/www/html/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
#      - ./html/:/var/www/html/
      - ./source/:/var/www/
      - ./source/public/:/var/www/html/
    networks:
      - backend

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - VIRTUAL_HOST=phpmyadmin.site
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - frontend
      - backend


networks:
  frontend:
    external:
      name: proxy_proxy
  backend:
